### ISSUE TITLE
Respect "shouldShowVariations"

### ISSUE THREAD

**Issue by keepcalm444** [quadrupleslap/sublimate#10]
<img src="http://puu.sh/cfBA9/59954fb101.png"></img> on Friday at 8pm ಠ_ಠ

>Please make sure you respect the "shouldShowVariations" response from the API or Mr Prorellis won't be impressed and you'll lose access to variation information entirely.

**Comment by gnustomp** [comment]
You're still not respecting it.

**Comment by quadrupleslap** [comment]
Suggest what it should do then. Turn pink? Use `<marquee>`? Spam popups saying that variation's aren't final? Put up a toast or something?

How on earth am I meant to know how to "respect" it. All I know is that hiding potentially useful data is not a nice thing to do.

**Comment by gnustomp** [comment]
Its kinda simple. Do not show variations unless it is true.

**Comment by quadrupleslap** [comment]
Nah, it's too complicated. If you want it so bad, plz pull request.

**Comment by gnustomp** [comment]
I didn't realise your code was _that_ bad. No thanks.

**Comment by quadrupleslap** [comment]
xD so you don't think it's a problem? Will close now, thanks.

**Comment by gnustomp** [comment]
No, it is an issue, but your broken code will stay broken, unless you fi

**Comment by quadrupleslap** [comment]
Umm, the code is hacked together in shoddy jQuery. It has bigger problems.
